---
include:
  - board: nice_nano_v2
    shield: tboard_central
    artifact-name: tboard-central
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: tboard_left
    artifact-name: tboard-left
  - board: nice_nano_v2
    shield: tboard_right
    artifact-name: tboard-right
