---
include:
  - board: nice_nano_v2
    shield: tboard_central
    artifact-name: tboard-central
  - board: nice_nano_v2
    shield: tboard_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y
    artifact-name: tboard-left
  - board: nice_nano_v2
    shield: tboard_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y
    artifact-name: tboard-right
